image: alpine

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  before_script:
  - apk add openssh
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  script:
    - ssh-add <(echo "$SSH_KEY")
    - ssh -o StrictHostKeyChecking=no  "$SSH_USER"@"$SSH_HOST" "cd $WORKDIR && git pull"