image: alpine

stages:
  - deploy

deploy:
  stage: deploy
  when: manual
  before_script:
  - apk add openssh
  - mkdir -p ~/.ssh
  - eval $(ssh-agent -s)
  script:
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add -
    - ssh -o StrictHostKeyChecking=no  "$SSH_USER"@"$SSH_HOST" "cd $WORKDIR && git pull"